version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    build: .
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    
    volumes:
      - ./:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db